#worst dorm
setwd("~/Documents/CSCI 183/")
bike_theft <- read.csv("Bike Theft Log (From Sept07).csv", header = TRUE, stringsAsFactors = FALSE)

table(bike_theft$LOCATION)

bike_theft$LOCATION= gsub("A & S bike rack", "A&S",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Arts & Science bike rack", "A&S",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Bannan Eng. Bike rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Bannan Engineering quad rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Bannan bike rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Bannan quad open area", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Benson Center bike rack", "Benson",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Benson bike rack", "Benson",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Benson outside of Bronco", "Benson",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Campisi Quad bike rack", "Campisi",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Campisi bike rack", "Campisi",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Campisi bike racks", "Campisi",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Casa Italiana bike rack", "Casa Italiana",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Casa bike rack", "Casa Italiana",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Casa west bike rack", "Casa Italiana",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Daly Sci. inside entry door", "Daly Science",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Daly Science 100 bike rack", "Daly Science",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Daly Science 200", "Daly Science",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Daly Science 300", "Daly Science",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Dunne Hall bike rack", "Dunne",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Dunne bike rack", "Dunne",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Engineering Lab bike rack", "Engineering",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Engineering Quad", "Engineering",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Graham 300 bike rack", "Graham",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Graham 400 bike rack", "Graham",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Graham bike rack", "Graham",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Heafey Law Library bike rack", "Heafey Library",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Heafey Library bike rack", "Heafey Library",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("IT Bannan lab", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("IT Bannan lab bike rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("IT bike rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("IT/Mech. Eng bike rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Locatelli bike rack", "Locatelli Center",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Malley Ctr. Bike rack", "Malley Ctr bike rack",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Mechanical Eng.rack", "Bannan Eng.",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Nobili Hall bike rack ", "Nobili Hall",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Nobili bike rack", "Nobili Hall",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Nobili/Adobe bike rack", "Nobili Hall",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("O'Connor Hall bike rack ", "O'Connor",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("O'Connor bike rack", "O'Connor",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("O'Connor west rail", "O'Connor",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sanfilipo outside", "Sanfilipo",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sanfilippo Ent. Wooden bench", "Sanfilipo",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sanfilippo bike rack", "Sanfilipo",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sanfilippo handicalp railing", "Sanfilipo",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sobrato bike rack", "Sobrato",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sobrato garage", "Sobrato",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sobrato north bike rack", "Sobrato",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sobrato south bike rack", "Sobrato",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Swig Hall bike rack", "Swig",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Swig bike rack", "Swig",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Univ. Villas bike rack", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Univ. Villas quad area", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("University Villas balcony", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("University Villas bike rack", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("University Villas inside", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Villa Apts. Bike rack", "Villas",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Walsh Hall HC Railing", "Walsh",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Walsh Hall bike rack", "Walsh",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Walsh bike rack", "Walsh",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Bannan Eng.", "Engineering",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Engineering bike rack", "Engineering",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Campisis", "Campisi",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Music & Dance bike rack", "Music & Dance",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Perf. Arts/Music & Dance", "Music & Dance",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Nobili Hall bike rack", "Nobili Hall",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("O'Connor Hall bike rack", "O'Connor",bike_theft$LOCATION)
bike_theft$LOCATION= gsub("Sobrato ", "Sobrato",bike_theft$LOCATION)

frequency <- table(bike_theft$LOCATION)
sort(frequency, decreasing= TRUE)


freq <- table(bike_theft$DATE)
#Worst Day
bike_theft$DATE <- as.Date(bike_theft$DATE, "%m/%d/%y")
bike_theft$day <- weekdays(as.Date(bike_theft$DATE))

worst_days <- table(bike_theft$day)
sort(worst_days, decreasing= TRUE)

#Worst Month
sort(freq, decreasing=TRUE)
bike_theft$months <- format.Date(as.Date(bike_theft$DATE), "%m") 
sort(table(bike_theft$months), decreasing=TRUE)